// Generated by Selenium IDE
const { Builder, By, Key } = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');
const assert = require('assert');

describe('E2E Test', function () {
    this.timeout(30000);
    let driver;
    let vars;

    beforeEach(async function () {
        // Set Firefox options
        let options = new firefox.Options();
        options.addArguments('-headless'); // Run in headless mode for CI environments

        // Initialize the Firefox WebDriver
        driver = await new Builder()
            .forBrowser('firefox')
            .setFirefoxOptions(options)
            .build();

        driver.manage().setTimeouts({ implicit: 0 });
        vars = {};
    });

    afterEach(async function () {
        if (driver) {
            await driver.quit();
        }
    });

    it('Should add a task', async function () {
        // Navigate to the application
        await driver.get("http://localhost:3000/");
        await driver.manage().window().setRect({ width: 1510, height: 871 });

        // Perform actions on the page
        await driver.findElement(By.css("input")).click();
        await driver.findElement(By.css("input")).sendKeys("this is a task");
        await driver.findElement(By.css("button:nth-child(2)")).click();
        await driver.findElement(By.css("button:nth-child(3)")).click();
        await driver.findElement(By.css("button:nth-child(4)")).click();
    });
});
