name: Build and Test on Dev Merge

on:
  push:
    branches: [ "dev", "main" ] # Triggered when there is a push in dev branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check the code
        uses: actions/checkout@v4 # Check the code
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # Install packages in the backend, frontend, and e2e-tests
      - name: Install packages in the backend
        working-directory: backend
        run: npm i
        
      - name: Install packages in the frontend
        working-directory: frontend
        run: npm i

      - name: Install packages in the e2e-tests
        working-directory: e2e-tests
        run: npm i

      - name: Install mocha globally for E2E tests
        run: npm i -g mocha

      # Run tests in the backend, frontend, and e2e-tests
      - name: Run tests in the backend
        working-directory: backend
        run: npm test
        
      - name: Run tests in the frontend
        working-directory: frontend
        run: npm test

      # Start the backend and frontend before running E2E tests
      - name: Start backend
        working-directory: backend
        run: npm start & # Start backend in the background

      - name: Start frontend
        working-directory: frontend
        run: npm start & # Start frontend in the background

      # Wait for the servers to start
      - name: Wait for services to be ready
        run: npx wait-on http://localhost:3000

      # Run E2E tests
      - name: Run E2E tests
        working-directory: e2e-tests
        run: npm test

  auto-merge:
    name: Auto-Merge Dev into Main
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() # Only run if the build-and-test job succeeds
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 2: Configure Git for the action
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Force push dev to main
      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      

